#!/usr/bin/env bash
# PostToolUse hook for Bash: when a `git commit` command just succeeded,
# if the current branch has a corresponding docs/features/<branch>.md,
# append a "Commit log (auto-appended)" entry with SHA, subject, and
# diff stats. Silent on success and on skip.

set -u

input="$(cat)"

cmd="$(printf '%s' "$input" | jq -r '.tool_input.command // ""')"
[ -n "$cmd" ] || exit 0

# Only run when the command actually invokes `git commit` (anywhere in the
# command — also catches `git add ... && git commit ...`). Exclude
# commit-adjacent commands that contain the substring but aren't a commit.
printf '%s' "$cmd" | grep -qE '(^|[[:space:];&|`])git[[:space:]]+commit([[:space:]]|$)' || exit 0

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
branch="$(git -C "$repo_root" rev-parse --abbrev-ref HEAD 2>/dev/null)" || exit 0

# Skip default/long-lived branches.
case "$branch" in
  main|master|develop|dev|trunk|HEAD) exit 0 ;;
esac

target_file="$repo_root/docs/features/$branch.md"
[ -f "$target_file" ] || exit 0

# Gather commit metadata. Bail if HEAD isn't a real commit (initial state).
sha="$(git -C "$repo_root" rev-parse --short HEAD 2>/dev/null)" || exit 0
[ -n "$sha" ] || exit 0
subject="$(git -C "$repo_root" log -1 --pretty=%s HEAD 2>/dev/null)" || exit 0
author_date="$(git -C "$repo_root" log -1 --pretty='%ad' --date=iso-strict HEAD 2>/dev/null)" || exit 0
stat="$(git -C "$repo_root" show --stat --format= HEAD 2>/dev/null)" || exit 0

section_header="## Commit log (auto-appended)"

# Idempotency: never append the same SHA twice. Scope the check to lines
# below the auto-append section header — mentions of the SHA in earlier
# narrative (e.g. an author-written "Commits" section) must not block us.
if sed -n "/^${section_header}\$/,\$p" "$target_file" 2>/dev/null | grep -qF "$sha"; then
  exit 0
fi

# Ensure the auto-append section header exists.
if ! grep -qF "$section_header" "$target_file" 2>/dev/null; then
  {
    printf '\n'
    printf '%s\n' "$section_header"
    printf '\n'
    printf '_Auto-generated by .claude/hooks/append-commit-to-md.sh on each \`git commit\`. Newest entries at the bottom._\n'
  } >> "$target_file"
fi

# Append the new entry.
{
  printf '\n'
  printf '### %s · %s\n' "$sha" "$author_date"
  printf '\n'
  printf '%s\n' "$subject"
  printf '\n'
  printf '```\n'
  printf '%s\n' "$stat"
  printf '```\n'
} >> "$target_file"

exit 0
